apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: storage
  labels:
    app: redis
    kubernetes.io/name: "redis"
spec:
  selector:
    app: redis
  type: LoadBalancer
  loadBalancerIP: 192.168.1.205
  ports:
  - name: redis
    port: 6379

---