apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: googlefit
  name: googlefit-data
  namespace: iot
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi