apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: logdna-secret
  namespace: alerting
spec:
  encryptedData:
    key: AgA+5AjdEdwF69PCh+XV/WHSI5VYMsvzUxoQyruxMP3evX3jwsjVPV9WTtdjvK7pUuSby60+V/lv/g97yUuJBMjbeN5hpT3HmpzuOcKyCY7KmGuonqKD3ZbtxvMjSBK/1xi88DKb/DI/31qSMWZ4vX//kg1hhzgGtvhmKRK/7m8Av/xQ0fB5rcOyKpehphsRx5loOaPincttMnn6ThsI4s+oXsZKHDE/odWRfjTOoEZzRje+DzTM8QZv3TcIhhQ5B7kFRs648A841CK00WiS6AGS+o3LB0rFSadOV03iOeIhUnH121Vl9gpvT2fiVFLhXl9y449dvR+0gNFyojYn9ijV68T+GGQ8tYJSksa9CLiFVFSOJRv791rZe/rfANYFv7yXWKcdGFbifik5rk0bNojds3WOyTjyE1lr0bxqcxU9Ix+BAEPb7aA9l9dt946pcfKJVuApCY9LyzStcSjBk25+PV0ac23rJxztFQj/bgDE76D/SDEtd3xsgWfX3sj4+qmgAwJzEL7UbeolF3D0hgb8TzCOSNgSLkZE0U6E/+YBPH854m+J5J1qsAsxfbRuCP/bO8aDD8UsFfwX3iTUwQE6OqbYUpi/zMD2F8PolupjNyRzikpIvT6ap8o+YBDyiYDI/8jxZ+AGX8fzYFzXyjYMXLC+Yv+KXBohlN4+iHdn7GE+rhIZlAjPFRmQjtWa69IwTIzPfU/G8/YJF7ZHr8JG4o5kZGtQaxU=
  template:
    metadata:
      creationTimestamp: null
      name: logdna-secret
      namespace: alerting

