apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: logdna-secrets
  namespace: alerting
spec:
  encryptedData:
    LOGDNA_AGENT_KEY: AgBl+AqI0dTO4EW7llZajW6ZP3+7Zou7w3N60xnc4HK+bEDYhKkpFuqpoZOxHcFY+faY8WRB8N86NRw41g8w7IQuY1HWjtowvdPVs6HHPDQ7vhzlCJezziHX+q6xEbnnno7+S8JiVEP59j25J93XbDIb4eamoiY2ZzAgK/iTPOfQFg8hjy4Bcui0++ljzeIZ/hgFIHksIATb4m0QUBDEi5Xh8AhBqhA63aEG4dFsfvID4aGGMsjBcy1Ba8wTQ1FQx0ySOwZyhvg9FCi4pHv9DVN/Ge7hDf5pje7NqlkP7ct7xyYCkOn1Q15VEGzXUAsdH/1TxoPMSH6Y4VWUiPlJIXf/x6s6z3Q7xsca6NBhTuDR22FKWUk9GgX1mkdgGGi+YpULSK3GzoPmrnJ0tIKMHOfXPpD12bcCDLq5JnV5bp46zHk6vH2r44ja40uFrOiBAPlwG0m+KZLfBLQKXyI5NnDb41kNd/FPBNbDv5kmDScncU+UI5mXjayj14/vadGtRP0wFMG7ap3hYpkEFUU3Af3L81g56BLmz/vikOWys5kA4uDZ0S0eE7kvgzwsMaMEiAJQ2nDJsUpm8wiHrQdL8qTIMqcxXCx5xJA0fkBERznCAA/Cnt9ZFaaSqXATiB5nkT7dsW6hoEq+eOy2eIvqjp73hZ2Gz7S0cVNd4g5uKNm1mBLSnDy9xPxu17nA1MHy/nz2LXzYFqIxvbervET2jYuZyo1eu6Av647O7h+E8xVc1A==
  template:
    metadata:
      creationTimestamp: null
      name: logdna-secrets
      namespace: alerting
    type: Opaque

