---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: actions-secrets
  namespace: automation
spec:
  encryptedData:
    NODE_RED_CREDENTIAL_SECRET: AgB0eUuOohM6CaafLjcTBDCorlj8Ldje8VZISdzLpBRVp4NsQWiXLGH4OrGr767mxOrrDG0eaE21bOXTY02004F0f2M72zt9m6Zo5YRRVI0wO2UDaMwlNjZe1TGXrMtSvSgbO8TdHfB3+CJIj9qeBykNHOmu1TyDYwsQLWqqtVsJU4ly3iC+TKsV58hSil26/f3a1wzlS479ms/0d0fkUAIg1iSDm7gBUhAU0oFS1Ir2YYO3r66ZATBczZAWJxHoupCpLYO9xuAcvM0QIeHLh7RDZfp/FRI8WTNI+kUjCaJFBtH6P99IGuvPYGA7Kl0NkSaBRxARcXvheXu2RP5zoubM7JAHzCLRm/Z1ds+9VKXacUK+XlbMASVz9ccH5tMpHm8Vd7XrW7JUkmVInuuRsc6QcDF/cGEuDD+07Asz3Lxh7Pjh6RrsfONB2PUhGNrUPTUTe4sZgokEtyBQh/yp2KIu1d5fxyiLHqUUiJwiXRTbpV2Ghrui2pvrJM3ZSnhGPJkFINB45a2kI0WzU3oBNIZyyrN+yjZ6hjn/RuvW6BZCMoh2CgCgrh9Fnlot9sNW94EXW/W6EB/qk1d2vt+MfMc4+28FVWNuW7hhFtx4IMAw4oGRJySjlwOyqUMtAS5FYPoL+aPfk5D0SoWJ0WPYTmsSADRMSqI5Lc11WqG9veHhHX8LsCPNt25fXk1hviBGbu8za/ujmSuBPlebBqlVo5o=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: actions-secrets
      namespace: automation
    type: Opaque
