apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-clean
  namespace: storage
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: arm32v7/alpine
            name: backup-clean 
            command: ["/backup-clean.sh"]    
            envFrom:
            - secretRef:
                name: backup-secrets
            volumeMounts:
            - mountPath: /backup-clean.sh
              name: backup-clean-config
              subPath: backup-clean.sh
              readOnly: true
          volumes:
          - name: backup-clean-config
            configMap:
              name: backup-clean-config
              defaultMode: 0777
          restartPolicy: Never
      backoffLimit: 0

