apiVersion: v1  
kind: Service  
metadata:  
  name: influxdb-service  
  namespace: storage
spec:  
  selector:  
    app: influxdb  
  ports:  
    - name: http
      protocol: TCP
      port: 8086  
      targetPort: 8086
    - name: rpc
      port: 8088 
      targetPort: 8088