apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: airflow
  name: airflow-logs-pvc
  namespace: actions
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

