kind: ServiceAccount 
apiVersion: v1 
metadata:
  labels:
    name: airflow
  name: airflow-scheduler 
  namespace: actions

---

kind: ClusterRole 
apiVersion: rbac.authorization.k8s.io/v1 
metadata: 
  labels:
    name: airflow
  name: airflow-role 
rules: 
  - apiGroups: [""] 
    resources: ["services", "endpoints", "pods"] 
    verbs: ["get", "list", "create", "delete", "watch", "patch"] 
  - apiGroups: [""] 
    resources: ["pods/log"] 
    verbs: ["get", "list", "create", "delete", "watch", "patch"] 
  - apiGroups: [""] 
    resources: ["pods/exec"] 
    verbs: ["get", "list", "create", "delete", "watch", "patch"] 
  - apiGroups: [""] 
    resources: ["events"] 
    verbs: ["list"] 


---

kind: ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1 
metadata: 
  labels:
    name: airflow
  name: airflow-rolebinding 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: airflow-role 
subjects: 
  - kind: ServiceAccount 
    name: airflow-scheduler 
    namespace: actions