apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  namespace: automation
spec:
  selector:
    app: airflow
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      
