kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: airflow-worker 
  namespace: actions 
  labels:
    app: airflow
    component: worker
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: airflow 
      component: worker
  template: 
    metadata: 
      labels: 
        app: airflow 
        component: worker
    spec: 
      serviceAccountName: airflow-scheduler
      nodeSelector:
        arm64: "true"
      initContainers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v3.6.8
          env:
          - name: GIT_SYNC_BRANCH
            value: "master"
          - name: GIT_SYNC_REPO
            value: "https://github.com/cwilko/smart-home-config"
          - name:  GIT_SYNC_ROOT
            value: "/git"
          - name:  GIT_SYNC_DEST
            value: "smart-home-config"
          - name:  GIT_SYNC_ONE_TIME
            value: "true"
          volumeMounts:
            - name: airflow-resources
              mountPath: /git
      containers:         
        - name: airflow-worker 
          image: wilkobets/airflow:test
          imagePullPolicy: IfNotPresent 
          securityContext: 
            runAsUser: 50000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryKubernetesExecutor"
            - name: AIRFLOW__CELERY__BROKER_URL
              value: "redis://redis.storage.svc.cluster.local:6379/0"
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: "redis://redis.storage.svc.cluster.local:6379/0"
            - name: AIRFLOW__CORE__DAGS_FOLDER 
              value: "/opt/airflow/sync/smart-home-config/workloads/airflow/dags"
            - name: AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE
              value: "Europe/London"
            - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
              value: "Europe/London"
          envFrom:
            - secretRef:
                name: airflow-secret
            - secretRef:
                name: airflow-econometrics-secret
          volumeMounts: 
            - name: airflow-logs-pv 
              mountPath: /opt/airflow/logs              
              readOnly: false 
            - name: airflow-resources
              mountPath: "/opt/airflow/sync"
              readOnly: true   
          command: 
            - airflow 
          args: 
            - celery
            - worker
      restartPolicy: Always 
      volumes: 
        - emptyDir: {} 
          name: airflow-resources
        - name: airflow-logs-pv 
          persistentVolumeClaim: 
            claimName: airflow-logs-pvc 