kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: airflow-worker 
  namespace: actions 
  labels:
    app: airflow
    component: worker
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: airflow 
      component: worker
  template: 
    metadata: 
      labels: 
        app: airflow 
        component: worker
    spec: 
      serviceAccountName: airflow-scheduler
      nodeSelector:
        arm64: "true"
      initContainers:
        - name: install-chromedriver
          image: wilkobets/airflow:latest
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: true
          command: ["/bin/bash", "-c"]
          args: 
            - |
              echo "Installing Chromium and ChromeDriver for ARM64..."
              apt-get update
              
              # Check what chromium packages are available
              echo "Available Chromium packages:"
              apt-cache search chromium | head -10
              
              # Try different package names
              apt-get install -y chromium chromium-driver || \
              apt-get install -y chromium-browser chromium-chromedriver || \
              apt-get install -y chromium-browser || \
              echo "No standard chromium packages found, trying alternative approach..."
              
              # If standard packages don't work, try to install from snap or download directly
              if ! command -v chromium &> /dev/null && ! command -v chromium-browser &> /dev/null; then
                echo "Installing chromium via snap..."
                apt-get install -y snapd
                snap install chromium
              fi
              
              echo "Checking installed files..."
              find /usr -name "*chrome*" -type f 2>/dev/null | head -10
              find /snap -name "*chrome*" -type f 2>/dev/null | head -5
              
              # Create directory structure in shared volume
              mkdir -p /shared/usr/lib/chromium-browser
              mkdir -p /shared/usr/bin
              mkdir -p /shared/snap/chromium/current/usr/lib/chromium-browser
              
              # Try to copy from various locations
              cp /usr/lib/chromium-browser/chromedriver /shared/usr/lib/chromium-browser/ 2>/dev/null || \
              cp /usr/bin/chromedriver /shared/usr/bin/chromedriver 2>/dev/null || \
              cp /snap/chromium/current/usr/lib/chromium-browser/chromedriver /shared/snap/chromium/current/usr/lib/chromium-browser/ 2>/dev/null || \
              echo "ChromeDriver not found in expected locations"
              
              # Copy chromium binary
              cp /usr/bin/chromium-browser /shared/usr/bin/ 2>/dev/null || \
              cp /usr/bin/chromium /shared/usr/bin/chromium 2>/dev/null || \
              cp /snap/chromium/current/usr/lib/chromium-browser/chrome /shared/usr/bin/chromium 2>/dev/null || \
              echo "Chromium binary not found in expected locations"
              
              # Make files executable
              chmod +x /shared/usr/lib/chromium-browser/chromedriver 2>/dev/null
              chmod +x /shared/usr/bin/* 2>/dev/null
              chmod +x /shared/snap/chromium/current/usr/lib/chromium-browser/chromedriver 2>/dev/null
              
              echo "Files in shared volume:"
              find /shared -type f 2>/dev/null | head -10
          volumeMounts:
            - name: chromedriver-shared
              mountPath: /shared
      containers:         
        - name: airflow-worker 
          image: wilkobets/airflow:latest
          imagePullPolicy: Always 
          securityContext: 
            runAsUser: 50000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryKubernetesExecutor"
            - name: AIRFLOW__CELERY__BROKER_URL
              value: "redis://redis.storage.svc.cluster.local:6379/0"
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: "redis://redis.storage.svc.cluster.local:6379/0"
            - name: AIRFLOW__CORE__DAGS_FOLDER 
              value: "/opt/airflow/sync/smart-home-config/workloads/airflow/dags"
            - name: AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE
              value: "Europe/London"
            - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
              value: "Europe/London"
            - name: AIRFLOW__CELERY__WORKER_CONCURRENCY
              value: "4"
          envFrom:
            - secretRef:
                name: airflow-secret
            - secretRef:
                name: airflow-econometrics-secret
          volumeMounts: 
            - name: airflow-logs-pv 
              mountPath: /opt/airflow/logs              
              readOnly: false 
            - name: airflow-resources
              mountPath: "/opt/airflow/sync"
              readOnly: true
            - name: chromedriver-shared
              mountPath: /shared
              readOnly: true   
          command: 
            - airflow 
          args: 
            - celery
            - worker
            - --queues=celery
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v3.6.8
          env:
          - name: GIT_SYNC_BRANCH
            value: "master"
          - name: GIT_SYNC_REPO
            value: "https://github.com/cwilko/smart-home-config"
          - name:  GIT_SYNC_DEST
            value: "smart-home-config"
          - name:  GIT_SYNC_ROOT
            value: "/git"
          - name:  GIT_SYNC_ONE_TIME
            value: "false"
          - name:  GIT_SYNC_WAIT
            value: "60"
          volumeMounts:
            - name: airflow-resources
              mountPath: /git
      restartPolicy: Always 
      volumes: 
        - emptyDir: {} 
          name: airflow-resources
        - name: airflow-logs-pv 
          persistentVolumeClaim: 
            claimName: airflow-logs-pvc
        - emptyDir: {}
          name: chromedriver-shared 