kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: airflow-worker 
  namespace: actions 
  labels:
    app: airflow
    component: worker
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: airflow 
      component: worker
  template: 
    metadata: 
      labels: 
        app: airflow 
        component: worker
    spec: 
      serviceAccountName: airflow-scheduler
      nodeSelector:
        arm64: "true"
      initContainers:
        - name: install-chromedriver
          image: wilkobets/airflow:latest
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: true
          command: ["/bin/bash", "-c"]
          args: 
            - |
              echo "Installing Chromium and ChromeDriver for ARM64..."
              apt-get update
              
              # Install both chromium and chromium-driver to get all dependencies
              echo "Installing chromium and chromium-driver..."
              apt-get install -y chromium chromium-driver
              
              echo "Checking installed ChromeDriver..."
              find /usr -name "chromedriver" -type f 2>/dev/null
              
              # Create directories in shared volume
              mkdir -p /shared/usr/bin
              mkdir -p /shared/usr/lib
              mkdir -p /shared/lib
              
              # Copy ChromeDriver to shared volume
              if [ -f /usr/bin/chromedriver ]; then
                echo "Found ChromeDriver at /usr/bin/chromedriver"
                cp /usr/bin/chromedriver /shared/usr/bin/chromedriver
                chmod +x /shared/usr/bin/chromedriver
                echo "ChromeDriver copied to shared volume"
              else
                echo "ChromeDriver not found at expected location"
                exit 1
              fi
              
              # Copy all required shared libraries based on ldd output
              echo "Copying required shared libraries..."
              
              # Get dependencies and copy them
              LIBS_TO_COPY="
                libatomic.so.1
                libgtk-3.so.0
                libgdk-3.so.0
                libgconf-2.so.4
                libxss1
                libxrandr2
                libasound2
                libpangocairo-1.0.so.0
                libatk-1.0.so.0
                libcairo-gobject2
                libgtk-3-0
                libgdk-3-0
                libpango-1.0.so.0
                libharfbuzz.so.0
                libcairo.so.2
                libgdk_pixbuf-2.0.so.0
                libgio-2.0.so.0
                libgobject-2.0.so.0
                libglib-2.0.so.0
              "
              
              # Find and copy each library
              for lib in $LIBS_TO_COPY; do
                # Search for the library in system paths
                LIB_PATH=$(find /lib /usr/lib -name "$lib*" -type f 2>/dev/null | head -1)
                if [ -n "$LIB_PATH" ]; then
                  echo "Copying $lib from $LIB_PATH"
                  # Preserve directory structure
                  LIB_DIR=$(dirname "$LIB_PATH" | sed 's|^/|/shared/|')
                  mkdir -p "$LIB_DIR"
                  cp "$LIB_PATH" "$LIB_DIR/"
                else
                  echo "Warning: $lib not found"
                fi
              done
              
              # Copy chromium binary as well
              if [ -f /usr/bin/chromium ]; then
                echo "Copying Chromium binary..."
                cp /usr/bin/chromium /shared/usr/bin/chromium
                chmod +x /shared/usr/bin/chromium
              fi
              
              echo "Installation and library copying complete!"
              echo "Verifying ChromeDriver dependencies..."
              ldd /shared/usr/bin/chromedriver || true
          volumeMounts:
            - name: chromedriver-shared
              mountPath: /shared
      containers:         
        - name: airflow-worker 
          image: wilkobets/airflow:latest
          imagePullPolicy: Always 
          securityContext: 
            runAsUser: 50000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryKubernetesExecutor"
            - name: AIRFLOW__CELERY__BROKER_URL
              value: "redis://redis.storage.svc.cluster.local:6379/0"
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: "redis://redis.storage.svc.cluster.local:6379/0"
            - name: AIRFLOW__CORE__DAGS_FOLDER 
              value: "/opt/airflow/sync/smart-home-config/workloads/airflow/dags"
            - name: AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE
              value: "Europe/London"
            - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
              value: "Europe/London"
            - name: AIRFLOW__CELERY__WORKER_CONCURRENCY
              value: "4"
          envFrom:
            - secretRef:
                name: airflow-secret
            - secretRef:
                name: airflow-econometrics-secret
          volumeMounts: 
            - name: airflow-logs-pv 
              mountPath: /opt/airflow/logs              
              readOnly: false 
            - name: airflow-resources
              mountPath: "/opt/airflow/sync"
              readOnly: true
            - name: chromedriver-shared
              mountPath: /shared
              readOnly: true   
          command: 
            - airflow 
          args: 
            - celery
            - worker
            - --queues=celery
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v3.6.8
          env:
          - name: GIT_SYNC_BRANCH
            value: "master"
          - name: GIT_SYNC_REPO
            value: "https://github.com/cwilko/smart-home-config"
          - name:  GIT_SYNC_DEST
            value: "smart-home-config"
          - name:  GIT_SYNC_ROOT
            value: "/git"
          - name:  GIT_SYNC_ONE_TIME
            value: "false"
          - name:  GIT_SYNC_WAIT
            value: "60"
          volumeMounts:
            - name: airflow-resources
              mountPath: /git
      restartPolicy: Always 
      volumes: 
        - emptyDir: {} 
          name: airflow-resources
        - name: airflow-logs-pv 
          persistentVolumeClaim: 
            claimName: airflow-logs-pvc
        - emptyDir: {}
          name: chromedriver-shared 