apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rpi-collector
  namespace: triggers
spec:
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      serviceAccountName: telegraf
      containers:
        - image: cwilko/telegraf:latest
          name: telegraf
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config
              subPath: telegraf.conf
              readOnly: true
            - mountPath: /host
              name: host-rootfs
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: docker
          env:
            - name: HOST_PROC
              value: "/host/proc"
            - name: HOST_SYS
              value: "/host/sys"
            - name: HOST_ETC
              value: "/host/etc"
            - name: HOST_VAR
              value: "/host/var"              
            - name: HOST_MOUNT_PREFIX
              value: "/host"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - secretRef:
                name: telegraf-secrets
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
        - name: host-rootfs
          hostPath:
            path: /
        - name: docker
          hostPath:
            path: /var/run/docker.sock

            
