---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-secret
  namespace: automation
spec:
  encryptedData:
    AIRFLOW__CORE__FERNET_KEY: AgBNKzChKah/JuWOBLpSeqCE42LP1qKi+DIaZmoqvvCJynK7MhPn3PVmF2PbzDMzbOh2wI1slD8zV/+iE6w7BBPwMLrg1sa+mK1THiXFl10+TzhPi6vLcIp0Na6c4MPlsii1txe7/nZnINTSSHbcoCY05LZyQStHoY5k/Wf+v2Dfg8p47cWYMp2Vj04CtFimr7ciGHPJJgtBlRaov70nFMTOXJdpbQuyBMPxNkQ0FV5xyEuwM3e1kwmmnvCQeKcbw8O8zy7nn0VN1r1jkoHZfhwTB5klZYt+OgddFUi/Fa01ekP+yfXjUyoCyOLxT7rZU09VYUPrl6sfA3prJ1LcU3RoPUlopHlG7P9M4l3XMLORm8CiHwQFTKL5C/JGgB19lKY+VnscSwGZaLp6KdVdnalyW+7QtTRmk5ASj7LUix9GPrm0ZBdKFtHx3olx+HlnQRTOBP6qxROIMT6SJX8Qi3PERE9SMhFPY4lYnYzZTqRIkxvsKGXlSWrNGw/PB8dYM8rJS9puoSylbYFvvA/60IXlGLRuvGo6gduW24AP6BgKusPajGzLTqL1a3CJMjgBi2CSLmtWWGxqLWy1mIDS4LHC8yaGj2djkbUL0WfmpfSOl/vrhS1eFym0kxI9QYkAWsx/leXp+NUbTwnjoZ+ZmeZn1S2XNGq3XKu8gNCzDsv5V7Gw71A3seQvbDJaAWM5b7KY71SOpRiXzbQW+Epe+DRefB7WPUTayErEiY8pH1XjqigEiUoVmvxyHLv8dQ==
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: AgBCkoZP2DrapkR7mQcpcuLZ0m84fSC+Gkx5MKc5o/qrhLI7VUbg8oN476mYxC/TNJcW4Ka5iDMOl2pkC7fF3o5aVFAlGIuItIK4ys0KemWhBWwVX1F+5yszr97+s9CqEdHGWOuEFUtQtLpMnJr9V2DR7tJjKVzlS4wFgFgiEP2POmvfzO53t2G0GxMz5LWhSGvcaZ4X3kwtlMuxurNppgw+tzut3TfgAk8nrWqlLgZy1chVSqq9/YkjmUtBHbwV2HS2Qno8ft3Z7LFerx/9cWYoN5W2Utxj4EujBLccqwtxiUzkVoeT4gXKV1DxPsmr53anj3GzXGC7TJYFjJeTFgcbLebcAczVGmQw+vHkNzjZquepufSO4JA+f2O4l/Co5I+jTNGBEETn7/hqVXyOzDKSMngB2VqE7hi8YSGHoqtI+FkbZV/ecMB8l2fEDyx1jZqlUhIB+yvf2Bn/B2PNGUB+6Ogl/YAoJsEeYh80T9/ffZijvOJtadDXpvpJcjCBckTk5erjt+3Tt5M8RIWwjqoZCHALC9hYKrrxnOSpVfQhbrPZv1Tei3NvHH49uqFih468UJOc18c0hdL7wyQce10bcDtDj8gV8aN3ku7x19V1F4l3/9l1AzP4Uw1Q0Jf4Bc+RRnLuubjDrvuBSwznuAxX1ksyL8R/rZEUfACE/J5qHyw5yfMHKfOjCw2Lp0Kyo70skiXcwP0tyJAQye6K03/z6tKXGDHskhP6fao1C19IF34/TRyEOHYE3C2MZNEPyT/Sc5osKXcEX1BZC2fY/bEwUAWAmuPAtdZ6cdFv
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-secret
      namespace: automation
    type: Opaque
