apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kapacitor
  name: kapacitor-scripts
  namespace: automation
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi