{
 "title": "CCTV",
 "description": "Analysis server monitoring by telegraf",
 "tags": [
  "telegraf",
  "influxdb",
  "home"
 ],
 "time": { "from": "now-24h", "to": "now-30s" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,20s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Battery Level",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"batteryLevel\") FROM \"arlo\" WHERE $timeFilter GROUP BY \"device\",time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Signal Strength",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"signalStrength\")/3 FROM \"arlo\" WHERE $timeFilter GROUP BY \"device\",time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connection State",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"connectionState\") FROM \"arlo\" WHERE $timeFilter GROUP BY \"device\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Camera Activity",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"motion\") FROM \"arlo\" WHERE $timeFilter GROUP BY \"device\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Driveway",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "content": " \n![alt text][logo]\n\n[logo]: https://freedomvms.com/samples/images/FreedomServer_Rear%20Car%20Park_HDBW3202P_1.jpg\n",
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"motion\") FROM \"arlo\" WHERE $timeFilter GROUP BY \"device\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Front Door",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "content": " \n![alt text][logo]\n\n[logo]: https://i.ytimg.com/vi/2OerRpq_OQQ/maxresdefault.jpg\n",
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"motion\") FROM \"arlo\" WHERE $timeFilter GROUP BY \"device\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Back Door",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "content": " \n![alt text][logo]\n\n[logo]: https://alertwatch.ie/wp-content/uploads/2014/07/Home-CCTV.jpg\n",
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"motion\") FROM \"arlo\" WHERE $timeFilter GROUP BY \"device\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}