{
 "title": "Heating",
 "description": "Analysis server monitoring by telegraf",
 "tags": [ "home" ],
 "time": { "from": "now-24h", "to": "now-30s" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,20s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Home Thermostat",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Kitchen Temperature",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"temperature\") FROM \"hive\" WHERE \"device\" = 'Thermostat 2' and $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Target Temperature",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"targetHeatTemperature\") FROM \"hive\" WHERE \"device\" = 'Thermostat 2' and $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heating",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Hot Water",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT max(\"stateHotWaterRelay\") FROM \"hive\" WHERE \"device\" = 'Thermostat 1' and $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Central Heating",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT max(\"stateHeatingRelay\") FROM \"hive\" WHERE \"device\" = 'Thermostat 2' and $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Connection",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "Hive Hub",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT min(\"presence\") FROM \"hive\" WHERE \"device\"='Hub' and $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Thermostat",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT min(\"presence\") FROM \"hive\" WHERE \"device\"='Thermostat 3' and $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Receiver",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT min(\"presence\") FROM \"hive\" WHERE \"device\"='Receiver 1' and $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Hive Server",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT min(\"serverConnectionState\") FROM \"hive\" WHERE \"device\"='Hub' and $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thermostat Battery",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "Kitchen Thermostat",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"batteryLevel\") FROM \"hive\" WHERE \"device\"='Thermostat 3' and $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}