{
 "title": "Kubernetes Pods",
 "description": "Kubernetes Aggregated Container Stats by Namespace and Container",
 "tags": [
  "kubernetes",
  "influxdb",
  "Container",
  "Telegraf",
  "system"
 ],
 "time": { "from": "2026-02-02T21:36:24.236Z", "to": "2026-02-02T23:25:50.418Z" },
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": "SHOW TAG VALUES FROM \"kubernetes_pod_container\" WITH KEY=namespace"
   },
   {
    "name": "name",
    "label": "Container Name",
    "query": "SHOW TAG VALUES FROM \"kubernetes_pod_container\" WITH KEY=container_name WHERE \"namespace\" =~ /^$ns$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "query": "SELECT count(pod_name) FROM (SELECT mean(\"cpu_usage_core_nanoseconds\") AS \"mean_cpu_usage_core_nanoseconds\" FROM \"kubernetes_pod_container\" WHERE time > now() - 1m AND namespace =~ /^$ns$/ AND container_name =~ /^$name$/ GROUP BY time(1h), \"pod_name\" LIMIT 1) FILL(previous)",
     "select": [
      [
       { "params": [ "cpu_usage_core_nanoseconds" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pod State",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod' AND \"labels\" =~ /k8s-app:fluentd-logging,/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/^$name/" },
      { "condition": "AND", "key": "namespace", "operator": "=~", "value": "/^$ns$/" }
     ]
    }
   ]
  },
  {
   "title": "Pod Core Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"cpu_usage_nanocores\")  / 1000000 FROM \"kubernetes_pod_container\" WHERE (\"namespace\" =~ /^$ns$/ AND \"container_name\" =~ /^$name$/) AND $timeFilter GROUP BY time($__interval), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage_nanocores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$ns$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  }
 ]
}