{
 "title": "Satellite TV",
 "description": "Home cluster stats",
 "tags": [
  "telegraf",
  "influxdb",
  "host",
  "system"
 ],
 "time": { "from": "now-24h", "to": "now-30s" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Disk Usage ",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(used_percent) FROM \"disk\" WHERE \"host\" = 'Satelite-TV' and \"device\" != 'rootfs'  and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(used_percent) FROM \"mem\" WHERE \"host\" = 'Satelite-TV'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"load15\") FROM \"system\" WHERE \"host\" = 'Satelite-TV'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Temp ",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(value) / 1000 FROM \"cpu_temp\" WHERE \"host\" = 'Satelite-TV'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}