apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hive-secrets
  namespace: devices
spec:
  encryptedData:
    HIVE_PASSWORD: AgBrgiMlT5eHai7Do7qJWaNYwFHUtdEHPGV5/OwZdn+1knmItGne7N/bZFrqve48RebiMJwzZjnrEASkec6Rx+6pUWJFp51a1RWbkJSf9849sGkcFM2KkMCEN+e1z71GYFdhiEROJD39rI+g7IEngBJ+LWifa4nFJMwkIEASvK5rKD88YE56vZYRLNUa7M+NwIfzVTefwdHqUzFQTB91ZKJyVdMt7bgr3IrHnkdgvnY5/AzBK+dowGLvZ4ZH/2nHn0ZMC7ztsg7l0NJPSI0dw37XQ5LzffYnrVbysMS0YpEr8kJ0oFiCQi1FsYaZnLiTtY75Qp4v/UL95gMqhEmWEJ6zKsyvga0MFuXiSyi66t+DhGdvsYwjgGiTnFFM27jNNl+caJJ2ZEPje8WWVfCB1UJsALiV1EsAYKN/H4GyjXbd9m3RSV5YLGwruLzWUAsiXFZ4mfbiZ26OUCMcTnhjHqJfiC8z4N+d85YHX/bxwzv9pjn0IpUh+Y+IO8DhKHrLqSnn2/4MxZduGjmPuv6gL6PAuT0LMtFZm3O5Ms10T59fJ4YKSrKZDVIF7qZrZN1+24dywX0N/PspjBP30skTW+OTp67RjJBQIo2I/MbdTgRWRWCMGFYiSHp57QVZtpNBU+13PNjtg7wxKBl5E7E6uvmrWHGvEN80ehl3xUvF/YMndD2IZZ6qm9FVTPcLGlyuZoVwULoSwpMh4w==
    HIVE_USERNAME: AgB9zfF+hvhd56WJAQzh4+UJOVsuYuC2j1+Gyl73IShKIeUaFTC9jWjlMOK5KCQB+QRuSURrkUIzGgjWH15vQLySCe+d103HsFUBK2f1GCE39znlvrh+0A1XhLz983v1F67m5y7YosMIhOXHd1EAJ5ryLQ5SRCKQgaYVLOlrc3u3xgTFta38e9M9mslw4rwgU0alkvbrux6VsNjD6IgBVW7bNX4kcJ8r7sNAJZ6RLQ9XL3zScHEtZB5JLYorVXrYB0XThhLn1i9haWBQgjOwMB3Jww088KO8xnyC/ZqaB8NaU+9Ofp95y8O9/d9A2aVq9B7JFRdYg+107xjwIGLKk/a0eSD2rA1RCxRoliBhy+Ip7CBs5NXm8tfTgzJlRQrU1D0RsVnIzTtvdH+Qx6+rn10pJLE2pPmyc54sSw56eyLVLwF3Yzm4Fu0wfaxvFJbgFFv/1T+a6TwCM+Or8most8HG946qR5K+cmOr/Z5oBpWPJzIPj44MKDXUMGfi9wUh6u5vpU+8bQX/bnOwtKI78bMwLntjuA8LXfobo/nIwYEq20a0f5gsLm7eBImvFJ0/adq/b6PaoXgG+KhLp8csyIOOyM0BZXe8o+w6poULHQRq8uV4PGNcSX8bbGqBvkO5Owf0ygRLBmNRJXHXPrRzXt878lwpk1mYErAFtglErxPUa0OeESbSal/fdXyMR1ltWjUIboOfq31rR/K/NnFwweRMYhBC92cPqb6YYg==
  template:
    metadata:
      creationTimestamp: null
      name: hive-secrets
      namespace: devices
    type: Opaque
status: {}

