apiVersion: v1
kind: Service
metadata:
  name: marketinsights-api-service
  namespace: marketinsights
spec:
  selector:
    app: marketinsights-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000