apiVersion: v1
kind: Service
metadata:
  name: price-store-service
  namespace: marketinsights
spec:
  selector:
    app: marketinsights
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080