apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.203
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: grafana
spec:
  rules:
  - host: grafana.192.168.1.203.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-service
            port: 
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actions-ingress
  namespace: actions
spec:
  rules:
  - host: actions.192.168.1.203.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: actions-service
            port: 
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mi-price-store-ingress
  namespace: marketinsights
spec:
  rules:
  - host: pricestore.192.168.1.203.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: price-store-service
            port: 
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-mgr-ingress
  namespace: marketinsights
spec:
  rules:
  - host: portfolio-mgr.192.168.1.203.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-mgr-service
            port: 
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-server-ingress
  namespace: marketinsights
spec:
  rules:
  - host: model-server.192.168.1.203.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: model-server-service
            port: 
              number: 80




