apiVersion: v1
kind: Service
metadata:
  name: murmur
  namespace: murmur
  labels:
    app: murmur
    kubernetes.io/name: "murmur"
spec:
  selector:
    app: murmur
  type: LoadBalancer
  loadBalancerIP: 192.168.1.204
  ports:
  - name: murmur
    port: 64738

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: murmur
  namespace: murmur
spec:
  selector:
    matchLabels:
      app: murmur
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: murmur
    spec:
      containers:
        - image: cwilko/murmur-alpine-arm:arm32v7
          name: murmur
          ports:
          - containerPort: 64738
          imagePullPolicy: Always