# Template for adding econometrics environment variables to sealed secrets
# 
# To update the existing airflow-sealed-secret.yaml:
# 1. Unseal the existing secret to get current values
# 2. Add these new environment variables 
# 3. Re-seal with kubeseal
#
# Example command to create sealed secret:
# kubectl create secret generic airflow-secret \
#   --from-literal=AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="postgresql+psycopg2://..." \
#   --from-literal=AIRFLOW__CORE__FERNET_KEY="..." \
#   --from-literal=AIRFLOW__SMTP__SMTP_USER="..." \
#   --from-literal=AIRFLOW__SMTP__SMTP_PASSWORD="..." \
#   --from-literal=FRED_API_KEY="your_fred_api_key_here" \
#   --from-literal=BEA_API_KEY="your_bea_api_key_here" \
#   --from-literal=BLS_API_KEY="your_bls_api_key_here" \
#   --from-literal=POSTGRES_HOST="your_postgres_host" \
#   --from-literal=POSTGRES_DB="econometrics" \
#   --from-literal=POSTGRES_USER="your_postgres_user" \
#   --from-literal=POSTGRES_PASSWORD="your_postgres_password" \
#   --from-literal=POSTGRES_PORT="5432" \
#   --dry-run=client -o yaml | \
#   kubeseal --format yaml --cert public-key.pem > airflow-sealed-secret.yaml

# New environment variables to add:
new_variables:
  # API Keys for data collection
  FRED_API_KEY: "your_fred_api_key_here"
  BEA_API_KEY: "your_bea_api_key_here" 
  BLS_API_KEY: "your_bls_api_key_here"  # Optional
  
  # Database connection for econometrics data (preferred)
  DATABASE_URL: "postgresql://user:password@host:port/econometrics"
  
  # Alternative individual database parameters (fallback)
  POSTGRES_HOST: "your_postgres_host"
  POSTGRES_DB: "econometrics"
  POSTGRES_USER: "your_postgres_user"
  POSTGRES_PASSWORD: "your_postgres_password"
  POSTGRES_PORT: "5432"

# Note: You'll need to:
# 1. Get your API keys from the respective services
# 2. Configure your PostgreSQL database connection details
# 3. Re-seal the secret with kubeseal and your cluster's public key