apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf-deployment
  namespace: triggers
spec:
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      serviceAccountName: telegraf
      containers:
        - image: cwilko/telegraf:1.13.2-alpine-arm32v7
          name: telegraf
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config
              subPath: telegraf.conf
              readOnly: true
            - mountPath: /host/proc
              name: host-proc
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: docker
          env:
            - name: HOST_PROC
              value: "/host/proc"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - secretRef:
                name: telegraf-secrets
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
        - name: host-proc
          hostPath:
            path: /proc
        - name: docker
          hostPath:
            path: /var/run/docker.sock

            