apiVersion: v1  
kind: Service  
metadata:  
  name: kapacitor-service  
  namespace: alerting
spec:  
  selector:  
    app: kapacitor  
  ports:  
    - protocol: TCP  
      port: 9092  
      targetPort: 9092