apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kapacitor
  name: kapacitor-scripts
  namespace: alerting
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi