apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lgtv-secret
  namespace: devices
spec:
  encryptedData:
    keyfile-192.168.1.4: AgBSXX/usYW+3mKjLv60wROW87Do+iogNcvnfifCKdOkp2jQZapn+5EOkAokLCajIVVxIr4tanWm4pHLnRFhbQvPR2rowFgcoEvy9qr8EtlvH71pB7F7IBM9cFDkPE1Y4EA96H+EF57mKdOLQXWRNEgwkBDAbm7q0HFcbLcCiENp9GnTVUojYR3hs2ay/h9ER5rFsENrxKbxEa59Pb7cPxICWXD0JvmNN+52iJ9+7FfxPyU2RiJJ2U32r5X10LZ+SDrI+CELN+O4BgQQGGYhncLUnfgxxoWg2E8+W4GVA6O9F3wgfHieYn7O3AoRH4B2SHJuSqlntsXcWFu3hQwtGKB93LFJLnpkoxM9qePgutqpadUkpVZRWppnfba+MoTrZINIJ68SPSLV+texYjtr6EtJFkf3fY+76bPa+I4Wcc/+nE4su96nOMFKz6oM/E2oFc8NGm48fVIweJc9/d5jy0MIXFg9EIjr+cyBIJNAzjdACiFnZnvGfIRbOm9IYIsEl7y+XUxQUaJYr6mhChDvkvY8Vdp8xes45IvwyDHCg7vGDw5KkdP3256xfJQQu0O2+hf3CPDPscDdNWtBaUOqaQXWr+XSfFGiY8SrKo/VH8r5Yo6W2ocXbhuLV7ft1Tv3JOuyH4B3HT1vOKtvatu8fO9oO2J9LplV6SgWlXIMoCOD7ybzKqx6kv4XuOcEkR3uqzqRzTd7LL9ahIQZlLBYJfXri05qvYQzyuqKEFcpa+TQfA==
  template:
    metadata:
      creationTimestamp: null
      name: lgtv-secret
      namespace: devices

