apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lgtv-secret
  namespace: devices
spec:
  encryptedData:
    keyfile-192.168.1.4: AgBgleN8drvmOcfUNjd7SKiOWn0fY97DawocOY+7SNLZr0c1wRrWtY7fObDxBZGE4Fi1Fa92tG/tLZDdxlAWdhipibFPEFSc5S4hm+erqx0tmYYMtDkr49rX7ii7jCA5vytW8M1xYyIqY1VgDk6kH0GntNknAPuR3GN90l8Zpz7KInyw76UeAJ3kbHk3u2NKlfEPwES58grpX+fkPLHpg86tFYT6pJHLxCpfzNMtHhkQKZDflF812qk2zSMBCXYfwurTREYaP/a0AZxMEa0xbNXsn6PfSTnJYc9fwVi1JxLWLt4Vbnzs05OQN9N9Lu3IhL4od79v1bsdEBYPdFNAwF+T8+cYHYV30J4I3DF17Oqm5xsOqHU4otUS0v3YbO1l3TDgnPVbdd+Vcel5bzowOy4WeN9m6rhPAinlewUjpfDAiWbc4rzIiEszs4+gepe4K5DTHvgiDGeQpRHWGwxx3Anv0VeA7MxAAuTPvZfxtXTkaQZIXPBHx92URCQ0bLPsrVMDzeMH+ztXyRaZ9vxr4gjaHQu7fDyV9D+kj2mOeoD2qfnx23Phl8gu2203990nHTJqmQ6rcnUFsyhuvlBUkoBw9mnafML3XnxHZbfcs/jHoYgkzOjSsjFGG4lsbUU6tpQR/M1LOMKept8sDqrgTpqhgXD79WrAMYYKNxhzsCblboOYzy2tgta3YbWo2nL0ONGnrmjaPfIvxa7scnWIz4Fma6NJS7yVO40VGxc0PIz1Og==
  template:
    metadata:
      creationTimestamp: null
      name: lgtv-secret
      namespace: devices
status: {}

