apiVersion: v1 
kind: Pod 
metadata: 
  name: airflow-worker 
  namespace: actions 
spec: 
  initContainers:
    - name: git-sync
      image: registry.k8s.io/git-sync/git-sync:v3.6.8
      env:
      - name: GIT_SYNC_BRANCH
        value: "master"
      - name: GIT_SYNC_REPO
        value: "https://github.com/cwilko/smart-home-config"
      - name:  GIT_SYNC_ROOT
        value: "/git"
      - name:  GIT_SYNC_DEST
        value: "smart-home-config"
      - name:  GIT_SYNC_ONE_TIME
        value: "true"
      volumeMounts:
        - name: airflow-resources
          mountPath: /git
  containers: 
    - name: base 
      imagePullPolicy: IfNotPresent 
      image: 'apache/airflow:2.3.3'
      env: 
      - name: AIRFLOW__KUBERNETES__NAMESPACE 
        value: "actions" 
      - name: AIRFLOW__CORE__DAGS_FOLDER 
        value: "/opt/airflow/sync/smart-home-config/resources/airflow/dags" 
      - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS 
        value: "True" 
      - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE 
        value: "True" 
      envFrom:
        - secretRef:
            name: airflow-secret
      volumeMounts: 
        - name: airflow-logs-pv 
          mountPath: /opt/airflow/logs 
        - name: airflow-resources
          mountPath: "/opt/airflow/sync"
          readOnly: true  
  restartPolicy: Never 
  securityContext: 
    runAsUser: 50000 
  serviceAccountName: "airflow-scheduler" 
  volumes: 
    - name: airflow-resources
      emptyDir: {}
    - name: airflow-logs-pv 
      persistentVolumeClaim: 
        claimName: airflow-logs-pvc