apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres      
    spec:
      containers:
        - name: postgres
          image: postgres:12.15-bullseye
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1003
            runAsGroup: 100
          ports:
            - containerPort: 5432 
          envFrom:
            - secretRef:
                name: postgres-secret        
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
              readOnly: false
            - mountPath: /docker-entrypoint-initdb.d/init_airflow.sh
              name: postgres-config
              readOnly: true
              subPath: init_airflow.sh
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: postgres-config
          configMap:
            name: postgres-config 
