apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-config
  namespace: grafana
data:
  init_airflow.sh: |-
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER airflow_user WITH PASSWORD 'airflow_pass';
      CREATE DATABASE airflow_db;
      GRANT ALL PRIVILEGES ON DATABASE airflow_db TO airflow_user;
    EOSQL