apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: storage
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type: LoadBalancer
  loadBalancerIP: 192.168.1.206
  ports:
  - name: postgres
    port: 5432