apiVersion: v1
kind: Service
metadata:
  name: portfolio-mgr-service
  namespace: marketinsights
spec:
  selector:
    app: portfolio-mgr
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080