apiVersion: v1
data:
  server.ini: |+
    [MQTT]
    host = 192.168.1.202
    port = 1883
    topic = home/chromecast

    [CHROMECAST]
    device = Kitchen display
    #device = SHIELD

kind: ConfigMap
metadata:
  name: mqtt-chromecast-config
  namespace: actions
