---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAXKme1YjA4pokVXQ2/SEYXmA9vxJP4VZeL9Sp7yR+TF6D2CrxBMBheEywg3Mz8OUaOpAVhjSppBIoPvPnIgoM5o+kbccRmuI0evhJcTancPfAqmxOsT5XIZfNYyuB87jPlvRihVxi8jGo4K0J0RYAq9096+/zOW0hk2z3KPRvfs2CstjAp6hZcMf+qZdI4Zi1Qn7XeJY1Lc9HIzJGyV9+dgJbnESi7W35cZR+kENzVRU7NYz7zFT9PfrtzqFblW3ihbhbuhZnZa231lT2f3tAbpMDfvnFGOzBvjjh8HehauNndGK0WarZvG8pvQbcZ3r3ID+7ViIlpCxEDpLvWH7L75dUa2QuYIYU2PFt9dnKyq8+rNPcLSpEeNiJYnntqXpfxiutP4fa3VomuEWICmns8Pgse2/y+2cfwiX4ivq1Ok3E9rZkdd/zDnCiqwrIUgCAANZNevOHoMj0ggKkSw/LulJK3eNF+3kTA0JZnSFoXx3bAJH/B/PcgkxTK2R1xNSxzV5Yrbu1ulie+nXKdNadjdqGJDRZF+H2cO3RV7Fn78SkzaEjTQiW4tsN9NRnfbMoxSao7znsQBOHDsbHzC+P9z9hYMQckt7iyM1lYOoU4x9p+2gR3/nITisPZLyO0HBYoxy9wOK9KJvFE1g6boBe7wOSct7MlpUuPIha3zPmkZXPpEW238fNbYqx3DrDmbl6kq6CJw1c9Dt+SgW913CD77A==
    client_secret: AgC+cWGt/QU4CvHcdRAXeTtHgF3Hc8bvqaV07uYDACyD6FEBbokynRX6xXxT90fn3HePlvjSVUgVMzqq0KgW/BWbdZRQmFmu+ab/2GetT8oj2qRaycXTdCgACSMjbFarJeGzTh2urp+CreUX1y97eQIp/05ywXj2RtuQDvfLZjAE0SXvWWC+2v8Xi8f8FL/Ja1o2dtxlU6YS0NlAuYj6CvrfEnshNhGRWAdRdLSIYsCz6EhXzOcXWJGOEGQBc8wnCaMNUgdridUDMGnDw4CNr9bfB6H4dtpr59MwnyQP7lYxMjg2THa0nrBshHtZunjXZ79HKa7dVEUH5sqcpoRmeoGpSQThdN8S3x8A0gtSXVgXYPSk/OR7ZWIYOdvNuP3Mm+86iH+viXmAkqPXwIQTagzIEVWOV5zrqamAnPaBlKcJU3VKA+53vIPaj3QHsxtCOrgAK011Imu4eJXx1aRZocctwxcLKJUxf4YEtbHuXvwAzKYvhPAcIpPackjbSev2aK2eVMhaAlEodWbmtsuSuDObFu262V8EtH+CNJeCtiD1H7/jM4U+3PuEs8ej/+5FKn1O1An3LaPFeOXN2DNCykXanIvH5b2SaISXd3hkcEISBrjUbWVw1pcm3YYXSHoHqh/GMNpNq4R9szH46uFv2SGlU6CSY7xQKJKTli/K4zNJ3NwA82XTl551C0m5cbm4pz3iGy09d2WHkA6fywt5EVC2q5STGm9iArG62m9Po6KZ7p78TG1RshwDqTq2dPl0+YD+VjKg7eGfVSgtRF7RZXRd
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
