apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb-backup
  name: influxdb-backup-data
  namespace: storage
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 500Mi