apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: actions-secrets
  namespace: actions
spec:
  encryptedData:
    NODE_RED_CREDENTIAL_SECRET: AgAFfFX4YXn8wA41Cp7djgKm1Gv+hLAuXA+FF95PlDU76MDyLnr7+pP7gaRsBliXUe+E+mzmElWmxWSnAcqiRq+9JIE8hzwuoSRJNkg0C3PPU9L4zNH1zf+eIXIIOk+bL8lmlpa6jiTBAEM0rhvEDoiDyGCP6Qg9DL7w1Q6QophirUWgWNMoqqz/ad90aBBO5awbSKDS8q1a5mSN+AQGbT0yvrx7KNYNgDJQfor/COBiaIADLj0IXJhqAjn0Ki/O8Z/Xq/ozX6zoar/1Zmd9MnAowos9KmNj7L5dw0DmVx2jk6HI/+VLHI5Mt+pE9bebGzXTTei+WWn64AZ5UgDWq6wvAHbL9ZXyaC1u9JhIqgmitgVNajq5IjYeKVuQa/gA3JxItxwddjIoBEeu4iwjCTP0a6KVY2VlSGz3Ti4fA+Y8bXCMJCyh5uVOoVCM9mOsl2I66mqDrUSl4GjXOW0NyUgiuRzJzFF5sYzha0O80P91AAK/GBQanOphCPjDzjBCRMDQa2Tk2+R2xuU60otsez9ROumWTqMSGfI3wPC/r8SPQNzapx7WIeUOoWA06kk80l2xax7ZeLS2evxqGUoY93paoiGtcywAp9C5Efx8jK5PWElaOowdLftnX/5Pq3N2Uk3/HcGJVr0oHhJHyMcbw1Mb5xZy9hQVmhVNILqNhqQPTXYpz6q3wY4bDdXD6Ki68y3nTjei2CE23+JGSGS+6iU=
  template:
    metadata:
      creationTimestamp: null
      name: actions-secrets
      namespace: actions
    type: Opaque

