apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: actions
  name: actions-data
  namespace: actions
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi