apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb-backup
  name: influxdb-backup-data
  namespace: storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi