apiVersion: v1
kind: Service
metadata:
  name: actions-service
spec:
  selector:
    app: actions
  type: LoadBalancer
  loadBalancerIP: 192.168.1.201
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1880

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-deployment
  labels:
    app: actions
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions
  template:
    metadata:
      labels:
        app: actions
    spec:
      containers:
      - name: smart-home-actions
        image: cwilko/smart-home-actions:latest
        ports:
        - containerPort: 1880