apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    app: mosquitto
    kubernetes.io/name: "mosquitto"
spec:
  selector:
    app: mosquitto
  type: LoadBalancer
  loadBalancerIP: 192.168.1.202
  ports:
  - name: mosquitto
    port: 1883

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
 #       volumeMounts:
 #       - name: mosquitto
 #         mountPath: /srv/mqtt/config
 #       - name: localtime
 #         mountPath: /etc/localtime
 #       - name: mosquitto-data
 #         mountPath: /srv/mqtt/data
 #       - name: mosquitto-log
 #         mountPath: /srv/mqtt/log
 #     volumes:
 #     - name: mosquitto
 #       persistentVolumeClaim:
 #         claimName: mosquitto
 #     - name: mosquitto-data
 #       persistentVolumeClaim:
 #         claimName: mosquitto-data
 #     - name: mosquitto-log
 #       persistentVolumeClaim:
 #         claimName: mosquitto-log
 #     - name: localtime
 #       hostPath:
 #         path: /etc/localtime