apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-backup
  namespace: storage
spec:
  selector:
    matchLabels:
      app: influxdb-backup
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: influxdb-backup
    spec:
      containers:
        - image: arm32v7/influxdb:1.7.9
          name: influxdb-backup
          env:
            - name: INFLUXDB_BIND_ADDRESS
              value: "127.0.0.1:8088"
            - name: INFLUXDB_HTTP_ENABLED
              value: "false"
          envFrom:
            - secretRef:
                name: influxdb-secrets