apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: metallb
  name: metallb-system

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: mosquitto
  name: mosquitto

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: triggers
  name: triggers

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: actions
  name: actions

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: storage
  name: storage

