apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: metallb
  name: metallb-system

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: mosquitto
  name: mosquitto

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: sensors
  name: sensors

