apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: metallb
  name: metallb-system

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: mosquitto
  name: mosquitto

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: triggers
  name: triggers

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: actions
  name: actions

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: storage
  name: storage

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: grafana
  name: grafana

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: alerting
  name: alerting

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: devices
  name: devices

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: marketinsights
  name: marketinsights

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: murmur
  name: murmur


