apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: model-server
  name: model-server-data
  namespace: marketinsights
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi