apiVersion: v1
kind: Service
metadata:
  name: model-server-grpc-service
  namespace: marketinsights
spec:
  selector:
    app: model-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8500