apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: model-server
  name: model-server-data
  namespace: marketinsights
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi