apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vscode-env
  name: vscode-data
  namespace: dev
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi