apiVersion: apps/v1
kind: Deployment
metadata:
  name: arlo
  namespace: devices
spec:
  selector:
    matchLabels:
      app: arlo
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: arlo
    spec:
      restartPolicy: Always
      containers:
        - image: cwilko/arlo2mqtt
          name: arlo
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: mqtt-secrets    
          - secretRef:
              name: arlo-secrets
          env:
          - name: INTERVAL
            value: "300"
          volumeMounts:
          - mountPath: /usr/app/creds
            name: gmail-secret
            readOnly: true         
      volumes:         
      - name: gmail-secret
        secret:
          secretName: gmail-secret
          items:
          - key: gmail.credentials
            path: gmail.credentials
      
