apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: cwilko/grafana-arm-curl
          envFrom:
          - secretRef:
              name: grafana-secrets
          name: grafana
          volumeMounts:
          - mountPath: /etc/grafana/provisioning/datasources/influxdb-datasource.yaml
            name: influxdb-ds-secret
            readOnly: true
            subPath: influxdb-datasource.yaml
          - mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
            name: grafana-config
            readOnly: true
            subPath: dashboards.yaml
          - mountPath: /etc/grafana/provisioning/playlists/playlists.json
            name: grafana-config
            readOnly: true
            subPath: playlists.json
          - mountPath: /etc/grafana/grafana.ini
            name: grafana-config
            readOnly: true
            subPath: grafana.ini
          - mountPath: /var/lib/grafana/dashboards
            name: grafana-data
          lifecycle:
            postStart:
              exec:
                command: ["curl", "-X", "PUT", "-H", "\"Content-Type: application/json\"", "-d", "@/etc/grafana/provisioning/playlists/playlists.json"]
      restartPolicy: Always
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config 
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data           
      - name: influxdb-ds-secret
        secret:
          secretName: influxdb-ds-secret