apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana:6.6.0
          envFrom:
          - secretRef:
              name: grafana-secrets
          name: grafana
          volumeMounts:
          - mountPath: /etc/grafana/provisioning/datasources/influxdb-datasource.yaml
            name: influxdb-ds-secret
            readOnly: true
            subPath: influxdb-datasource.yml
          - mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
            name: grafana-config
            readOnly: true
            subPath: dashboards.yaml
          - mountPath: /var/lib/grafana/dashboards
            name: grafana-data
      restartPolicy: Always
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config 
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data           
      - name: influxdb-ds-secret
        secret:
          secretName: influxdb-ds-secret